<?php
/**
 * @category    Retargeting
 * @package     Retargeting_Tracker
 * @author      Retargeting <info@retargeting.biz>
 * @copyright   Copyright (c) Retargeting
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

class Retargeting_Tracker_DiscountsController extends Mage_Core_Controller_Front_Action
{
    public function indexAction() {
        echo 'Discounts!!!';
    }

    public function addDiscountCodeAction() {

        $params = $this->getRequest()->getParams();

        if ( isset($params['apikey']) && isset($params['name']) && isset($params['code']) && isset($params['discount']) && isset($params['type']) && isset($params['condition']) && isset($params['availability']) && isset($params['condition_amount']) ) {

            $userApiKey = Mage::getStoreConfig('retargetingtracker_options/discounts/discount_api_key');

            if ( $userApiKey != '' && $params['apikey'] == $userApiKey && $params['name'] != "" && $params['code'] != "" && $params['discount'] != "" && $params['type'] != "" && $params['condition'] != "" && $params['availability'] != "" && $params['condition_amount'] != "" ) {
                $name = htmlspecialchars($params['name']);
                $code = htmlspecialchars($params['code']);
                $discount = htmlspecialchars($params['discount']);
                $type = htmlspecialchars($params['type']);
                $condition = htmlspecialchars($params['condition']);
                $availability = htmlspecialchars($params['availability']);
                $conditionAmount = htmlspecialchars($params['condition_amount']);

                echo $this->generateRule($name, $code, $discount, $type, $condition, $availability, $conditionAmount);
            } else {
                echo json_encode(array(
                    "status" => false,
                    "error" => "0002: Invalid Parameters!"
                ));
            }

        } else {
            echo json_encode(array(
                "status" => false,
                "error" => "0001: Missing Parameters!"
            ));
        }
    }

    private function generateRule($name = null, $coupon_code = null, $discount = 0, $type = "fixed value", $condition = null, $availability = 1, $conditionAmount = 0)
    {
        if ( $name != null && $coupon_code != null && ( $type == "fixed value" || $type == "free shipping" || $type == "percentage" ) )
        {
            $rule = Mage::getModel('salesrule/rule');
            $customer_groups = array(0, 1, 2, 3);

            // discount name and init
            $rule->setName($name)
                ->setDescription("Autogenerated discount through Retargeting Discount API")
                ->setCouponType(2)
                ->setUsesPerCustomer(1)
                ->setUsesPerCoupon(1)
                ->setCustomerGroupIds($customer_groups) //an array of customer grou pids
                ->setIsActive(1)
                ->setConditionsSerialized('')
                ->setActionsSerialized('')
                ->setStopRulesProcessing(0)
                ->setIsAdvanced(1)
                ->setProductIds('')
                ->setSortOrder(0)
                ->setSimpleFreeShipping('0')
                ->setApplyToShipping('0')
                ->setIsRss(0)
                ->setWebsiteIds(array(1));

            // discount code
            $rule->setCouponCode($coupon_code);

            // discount amount
            $rule->setDiscountAmount($discount)
                ->setDiscountQty(null)
                ->setDiscountStep(0);

            // discount type
            switch ($type) {
                case 'percentage':
                    $rule->setSimpleAction('by_percent');
                    break;
                case 'free shipping':
                    $rule->setSimpleAction('by_fixed')
                        ->setSimpleFreeShipping('1')
                        ->setDiscountAmount(0);
                    break;
                case 'fixed value':
                    $rule->setSimpleAction('by_fixed');
                    break;
            }

            // discount availability
            $rule->setFromDate(date('Y-m-d'))
                ->setToDate(Date('Y-m-d', strtotime("+".$availability." days")));

            // discount conditions/actions
            if ($condition == "over") {
                $item_found = Mage::getModel('salesrule/rule_condition_product_found')
                    ->setType('salesrule/rule_condition_product_found')
                    ->setValue(1) // 1 == FOUND
                    ->setAggregator('all'); // match ALL conditions
                $rule->getConditions()->addCondition($item_found);

                $conditions = Mage::getModel('salesrule/rule_condition_product')
                    ->setType('salesrule/rule_condition_product')
                    ->setAttribute('quote_item_price')
                    ->setOperator('>=')
                    ->setValue($conditionAmount);
                $item_found->addCondition($conditions);

                $actions = Mage::getModel('salesrule/rule_condition_product')
                    ->setType('salesrule/rule_condition_product')
                    ->setAttribute('quote_item_price')
                    ->setOperator('>=')
                    ->setValue($conditionAmount);

                $rule->getActions()->addCondition($actions);
            }

            // save discount
            $rule->save();

            return json_encode(array(
                "status" => true
            ));
        }

        return json_encode(array(
            "status" => false,
            "error" => "0003: Invalid Parameters!"
        ));
    }
}