<?php
/**
 * @category    Retargeting
 * @package     Retargeting_Tracker
 * @author      Retargeting <info@retargeting.biz>
 * @copyright   Copyright (c) Retargeting
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

class Retargeting_Tracker_DiscountsController extends Mage_Core_Controller_Front_Action
{
    public function indexAction() {
        echo 'Discounts!!!';
    }

    public function addDiscountCodeAction() {

        $params = $this->getRequest()->getParams();

        if ( isset($params['key']) && isset($params['value']) && isset($params['type']) && isset($params['count']) ) {

            $userApiKey = Mage::getStoreConfig('retargetingtracker_options/token/token');

            if ( $userApiKey != '' && $params['key'] == $userApiKey && $params['value'] != "" && $params['type'] != "" && $params['count'] != "" ) {
                $name = 'RA-' . htmlspecialchars($params['type']) . '-' . htmlspecialchars($params['value']);
                $discount = htmlspecialchars($params['value']);
                $raDiscountType = htmlspecialchars($params['type']);
                $count = htmlspecialchars($params['count']);

                echo $this->generateRule($name, $discount, $raDiscountType, $count);
            } else {
                echo json_encode(array(
                    "status" => false,
                    "error" => "0002: Invalid Parameters!"
                ));
            }

        } else {
            echo json_encode(array(
                "status" => false,
                "error" => "0001: Missing Parameters!"
            ));
        }
    }

    private function generateRule($name = null, $discount = 0, $raDiscountType = 0, $count)
    {
        $availability = 100;
        $conditionAmount = 0;

        if ($raDiscountType == 0) $raDiscountType = "fixed value";
        if ($raDiscountType == 1) $raDiscountType = "percentage";
        if ($raDiscountType == 2) $raDiscountType = "free shipping";

        if ( $name != null && ( $raDiscountType == "fixed value" || $raDiscountType == "free shipping" || $raDiscountType == "percentage" ) )
        {

            $rule = Mage::getModel('salesrule/rule');

            $customerGroupColl = Mage::getModel('customer/group')->getCollection();
            $customer_groups = array();
            foreach($customerGroupColl as $group) {
                $customer_groups[] = $group->getCustomerGroupId();
            }

            //Get all Store Ids
            $storeIds = array();
            $allStores = Mage::app()->getStores();
            foreach ($allStores as $storeId)
            {
                $storeIds[] = Mage::app()->getStore($storeId)->getId();
            }


            // discount name and init
            $rule->setName($name)
                ->setDescription("Autogenerated discount through Retargeting Discount API")
                ->setCouponType(Mage_SalesRule_Model_Rule::COUPON_TYPE_AUTO)
                ->setUsesPerCustomer(1)
                ->setUsesPerCoupon(1)
                ->setCustomerGroupIds($customer_groups) //an array of customer grou pids
                ->setIsActive(1)
                ->setConditionsSerialized('')
                ->setActionsSerialized('')
                ->setStopRulesProcessing(0)
                ->setIsAdvanced(1)
                ->setProductIds('')
                ->setSortOrder(0)
                ->setSimpleFreeShipping('0')
                ->setApplyToShipping('0')
                ->setIsRss(0)
                ->setWebsiteIds($storeIds)
                ->setUseAutoGeneration(1);

            // discount code
            //$rule->setCouponCode($coupon_code);

            // discount amount
            $rule->setDiscountAmount($discount)
                ->setDiscountQty(null)
                ->setDiscountStep(0);

            // discount type
            switch ($raDiscountType) {
                case 'percentage':
                    $rule->setSimpleAction('by_percent');
                    break;
                case 'free shipping':
                    $rule->setSimpleAction('by_fixed')
                        ->setSimpleFreeShipping('1')
                        ->setDiscountAmount(0);
                    break;
                case 'fixed value':
                    $rule->setSimpleAction('cart_fixed');
                    break;
            }

            // discount availability
            $rule->setFromDate(date('Y-m-d'));

            $generator = Mage::getModel('salesrule/coupon_massgenerator');

            $parameters = array(
                'count'=>5,
                'format'=>'alphanumeric',
                'dash_every_x_characters'=>4,
                'prefix'=>'ABCD-EFGH-',
                'suffix'=>'-WXYZ',
                'length'=>8
            );

            $generator->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC);
            $generator->setDash(0);
            $generator->setLength(8);
            $generator->setPrefix('');
            $generator->setSuffix('');

            // Set the generator, and coupon type so it's able to generate
            $rule->setCouponCodeGenerator($generator);

            // save discount
            $rule->save();

            $codes = array();
            for($i = 0; $i < $count; $i ++) {
                $coupon = $rule->acquireCoupon(true);
                $coupon
                    ->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
                    ->save();
                $code = $coupon->getCode();
                $codes[] = $code;
            }

            $rule->setCouponType(2);
            $rule->save();
            header('Content-Type: application/json');
            return json_encode($codes);
        }

        return json_encode(array(
            "status" => false,
            "error" => "0003: Invalid Parameters!"
        ));
    }
}