<?php
/**
 * @category    Retargeting
 * @package     Retargeting_Tracker
 * @author      Retargeting <info@retargeting.biz>
 * @copyright   Copyright (c) Retargeting
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
	(function(){
	var ra = document.createElement("script"); ra.type ="text/javascript"; ra.async = true; ra.src = ("https:" ==
	document.location.protocol ? "https://" : "http://") + "retargeting-data.eu/" +
	document.location.hostname.replace("www.","") + "/ra.js"; var s =
	document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ra,s);})();
</script>