<?php
/**
 * @category    Retargeting
 * @package     Retargeting_Tracker
 * @author      Retargeting <info@retargeting.biz>
 * @copyright   Copyright (c) Retargeting
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
	<?php 
		$ra_key = Mage::getStoreConfig('retargetingtracker_options/domain/domain_api_key');
		$add_to_cart_id = Mage::getStoreConfig('retargetingtracker_options/more/cartid');
		$price_label_id = Mage::getStoreConfig('retargetingtracker_options/more/pricelabelid');
	?>
	<?php if ($ra_key && $ra_key != '') : ?>
	(function(){
	ra_key = "<?php echo $ra_key; ?>";
 	ra_params = {
	    add_to_cart_button_id: "<?php echo ($add_to_cart_id != '' && $add_to_cart_id) ? $add_to_cart_id : "add-to-cart-buttons" ?>",
	    price_label_id: "<?php echo ($price_label_id != '' && $price_label_id) ? $price_label_id : "price-box" ?>",
	};
	var ra = document.createElement("script"); ra.type ="text/javascript"; ra.async = true; ra.src = ("https:" ==
	document.location.protocol ? "https://" : "http://") + "tracking.retargeting.biz/v3/rajs/" + ra_key + ".js";
	var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ra,s);})();
	<?php else : ?>
		console.info('ra_key is not set.');
	<?php endif; ?>
</script>